import Random
using Test
using Serialization
using DataFrames
include("../disRNN_MP/agent/matching_pennies.jl")

mpt_tst_dat = joinpath(dirname(@__FILE__), "test_data", "matching_pennies_test.jls")

function runMP(n = 1000)
    mpt = MatchingPenneisTask()
    # MatchingPenneisTask(maxdepth::Integer = 4, alpha::Real = 0.05; choices::Tuple = (0,1))

    for i = 1:n
        run_step(mpt, rand([0, 1]))
    end
    return mpt
end

Random.seed!(1)
mpt = runMP(2000)
add_histseq_col(mpt)

# serialize(mpt_tst_dat, mpt)
mpt_s = deserialize(mpt_tst_dat)

@testset "test whether the simulation with same seed matches with previously recorded data generated by `run_step` and `add_histseq_col`" begin
    @test mpt.history == mpt_s.history
    # @test select(mpt.biasCount, Not([:detected_on, :signif_tris])) == mpt_s.biasCount
    @test mpt.biasCount == mpt_s.biasCount
    @test mpt.trialBias == mpt_s.trialBias
end;

select!(mpt.trialBias, Not(:histseq))
empty!(mpt.trialBias)
empty!(mpt.biasCount)
cal_MP_algs(mpt)
add_histseq_col(mpt)


@testset "test whether `cal_MP_algs` matches with bias data generated during simulation" begin
    @test mpt.history == mpt_s.history
    @test mpt.biasCount == mpt_s.biasCount
    # @test select(mpt.biasCount, Not([:detected_on, :signif_tris])) == mpt_s.biasCount
    @test mpt.trialBias == mpt_s.trialBias
end;